on:
    repository_dispatch: # API call to dispatch
        types: [incident_report]
jobs:
    handle-incident:
        runs-on: ubuntu-latest
        steps:
            - name: print incident details
              run: echo "Incident Report"
